### ISSUE TITLE
Header's length is blocking the content

### ISSUE THREAD

**Issue by jellynina** [jellynina/ide.ncku#3]
As title.
<img width="1680" alt="2017-12-04 11 25 43" src="https://user-images.githubusercontent.com/6845626/33557461-a6422788-d94a-11e7-8b66-d1613d51f29e.png">

完全不知道高度怎麼來的😱

**Comment by jellynina** [comment]
> hihi關於系網。我覺得我寫的header有些問題
> 第一個就是header跟content中間有很大的空白不知道應該怎麼拉近  

> 第二個是我的header想要讓他窄一點  但我調了參數  nav bar沒跟著移動是因為我區塊沒包到嗎？😭😭😭😭

by 相如

**Comment by jellynina** [comment]
```html
<p> <!-- 不必要的 p tag, 而且沒有closing tag -->
<style type="text/css">  <!-- type="text/css" 不需要可以拿掉-->
.header {
  padding:20px 0px 0px 30px;
  height:150px;
  position:fixed;
  top: 0px;
  left: 0px;
  right: 0px;  
  background-color: #ffff;
  max-width:1250px;
  margin: 0 auto;
}
.h1{
  padding:30px 0px 20px 0px;
}
.nav{
  float: right; /* 下面用了960gs, 那麼這邊就不應該使用float, 全面用960排版才不會暴走 */
  list-style-type: none;
  padding:0px 10px 0px 0px; 
  text-alight: center;
  display: block;
}
li {
  display:inline;
  padding:5px;  
}
</style>
<!-- 這堆p...全部不需要 -->
<!-- html --></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p> <!-- 不必要的 p tag, 而且沒有closing tag -->
<link href="css=960_12_col.css" rel="stylesheet" type="text/css" /></p> <!--外部CSS的置入要放在style 的第一行-->
<div class="header">
  <div class="container_12">
    <div class="grid_5">
      <h1>
        <a href="/bin/home.php">
          <img alt="成功大學工業設計系" class="logo-img" src="/ezfiles/417/1417/img/3131/logo.png" style="width: 200px; height: 83px;"
          />
        </a>
      </h1>
    </div>
    <div class="nav">
      <ul>
        <li>
          <a href="/bin/home.php ">首頁</a>
        </li>
        <li>
          <a href="/files/11-1417-83-preview.php?Lang=zh-tw">最新消息</a>
        </li>
        <li>
          <a href="/files/90-1417-1.php?Lang=zh-tw">系上成員</a>
        </li>
        <li>
          <a href="/files/90-1417-4.php?Lang=zh-tw">系上課程</a>
        </li>
        <li>
          <a href="/files/90-1417-5.php?Lang=zh-tw">學生實習工廠</a>
        </li>
        <li>
          <a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">招生資訊</a>
        </li>
        <li>
          <a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">表單下載</a>
        </li>
        <li>
          <a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">其他連結</a>
        </li>
      </ul>
    </div>
  </div>
</div>

<p>&nbsp;</p> 
<!--這行不必要-->
```

1. 因為你多了很多 `<p>&nbsp;</p>`  會佔用很多空間
2. 另外因為使用`float`，然後沒有讓 左右兩大區塊的內中垂直置中
3. 招生資訊, 表單下載, 其他連結 都是同一個連結＠＠？？？

**Comment by elluu** [comment]
招生資訊和表單下載的連結那邊要等明天鷹慈那邊給的資訊和需求，要重新幫招生資訊和表單下載做新的版面，所以先丟其他連結測試。

**Comment by jellynina** [comment]
@elluu 
好的，未完或是有問題的項目，到issue tab去建立新的issue，把它當作todo list, 並且記錄作業過程

**Comment by elluu** [comment]
@jellynina 
OK 非常感謝 😭

**Comment by jellynina** [comment]
## 已經修正完畢

過程如下：

### Html Code

```html
<div class="g-header-outline">
  <div class="g-header-position">
    <div class="g-header">
        <div class="head-col head-col-logo">
          <h1 class="h1"><a href="/bin/home.php"><img alt="成功大學工業設計系" class="g-logo-img" src="/ezfiles/417/1417/img/3131/logo.png"/></a></h1>
        </div>
        <div class="head-col head-col-nav">
          <ul class="head-nav-list">
            <li><a href="/bin/home.php ">首頁</a></li>
            <li><a href="/files/11-1417-83-preview.php?Lang=zh-tw">最新消息</a></li>
            <li><a href="/files/90-1417-1.php?Lang=zh-tw">系上成員</a></li>
            <li><a href="/files/90-1417-4.php?Lang=zh-tw">系上課程</a></li>
            <li><a href="/files/90-1417-5.php?Lang=zh-tw">學生實習工廠</a></li>
            <li><a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">招生資訊</a></li>
            <li><a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">表單下載</a></li>
            <li><a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">其他連結</a></li>
          </ul>
        </div>
    </div>
  </div>
</div>

```

## 用SCSS 比較快

使用VUE Template, scss 語法，預覽之後沒有問題，丟到[SassMeister](https://www.sassmeister.com/), 並且在把編譯好的CSS丟到[線上壓縮機](https://csscompressor.com/)壓縮之後再貼到ePage裡面

```scss
$g-max-width: 1200px;
$g-side-padding: 15px;
$g-head-index: 300;
@mixin reset{
  padding: 0;
  margin: 0;
  box-sizing: border-box;
  list-style: none;
}


.g-header-outline{
  width: 100%;
  position: relative;
  padding: 24px 0;
}

.g-header-position{
  width: 100%;
  display: block;
  position: fixed;
  top: 0;;
  left: 0;
  padding: 12px 0;
  z-index: $g-head-index;
  background-color: #FFF;
}
.g-header{
  width: 100%;
  max-width: $g-max-width;
  padding: 0px 6px;
  position: relative;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: #FFF;

  .h1{
    font-size: 18px;
  }
}

.g-logo-img{
  width: 200px;
  height: 83px;
}

.head-col-logo{
  flex-grow: 1;
}
.head-col-nav{
  flex-grow: 2;
}

.head-nav-list{
  @include reset();
  display: flex;
  justify-content: flex-end;
  li{
    padding: 0 6px;
  }
}



```



## 最終結果的code

```html
<style>
.g-header-outline{width:100%;position:relative;padding:24px 0}.g-header-position{width:100%;display:block;position:fixed;top:0;left:0;padding:12px 0;z-index:300;background-color:#FFF}.g-header{width:100%;max-width:1200px;padding:0 6px;position:relative;margin:0 auto;display:flex;justify-content:space-between;align-items:center;background-color:#FFF}.g-header .h1{font-size:18px}.g-logo-img{width:200px;height:83px}.head-col-logo{flex-grow:1}.head-col-nav{flex-grow:2}.head-nav-list{padding:0;margin:0;box-sizing:border-box;list-style:none;display:flex;justify-content:flex-end}.head-nav-list li{padding:0 6px}
</style>    
    <div class="g-header-outline">
      <div class="g-header-position">
        <div class="g-header">
            <div class="head-col head-col-logo">
              <h1 class="h1"><a href="/bin/home.php"><img alt="成功大學工業設計系" class="g-logo-img" src="/ezfiles/417/1417/img/3131/logo.png"/></a></h1>
            </div>
            <div class="head-col head-col-nav">
              <ul class="head-nav-list">
                <li><a href="/bin/home.php ">首頁</a></li>
                <li><a href="/files/11-1417-83-preview.php?Lang=zh-tw">最新消息</a></li>
                <li><a href="/files/90-1417-1.php?Lang=zh-tw">系上成員</a></li>
                <li><a href="/files/90-1417-4.php?Lang=zh-tw">系上課程</a></li>
                <li><a href="/files/90-1417-5.php?Lang=zh-tw">學生實習工廠</a></li>
                <li><a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">招生資訊</a></li>
                <li><a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">表單下載</a></li>
                <li><a href="http://www.ide.ncku.edu.tw/sposad/" target="_blank">其他連結</a></li>
              </ul>
            </div>
        </div>
      </div>
    </div>
```


@elluu 麻煩review, 看有沒有要修正的地方，如果沒有，那麼我們就把這個issue結束掉
